<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="siteweb" nsURI="http://www.example.org/siteweb" nsPrefix="siteweb">
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="corps" lowerBound="1" eType="#//Corps"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entête" lowerBound="1"
        eType="#//Entête" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entête">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hyperlien" upperBound="-1"
        eType="#//HyperLien" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Corps">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocs" upperBound="-1"
        eType="#//Bloc" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//Bloc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocs" upperBound="-1"
        eType="#//Bloc" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloc" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Titre" eSuperTypes="#//Bloc">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="niveau" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paragraphe" eSuperTypes="#//Bloc"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="page" eType="#//Page"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contenu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Site">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HyperLien" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boutton" eSuperTypes="#//Action"/>
</ecore:EPackage>
